### ISSUE TITLE
Implement Account creation flow for Sign up

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-kotlin#679]
**Task**

Sign up flow for Account creation:

- [ ] Splash view
- [ ] New User/Existing User view
- [ ] Code view (will be used for invite or self sign up code later, but skipped for now)
- [ ] Connecting View (generate seed, connection to MQTT, subscription to owner ok key topics, publish to register and get balance, store response on owner record)
- [ ] Alias form view
- [ ] Profile Picture view
- [ ] Ready to use Sphinx -> Dashboard

**Acceptance Criteria**

- Write tests for each stage of the flow so we can test independently

**Comment by ariel10aguero** [comment]
@tomsmith8 we have changed a little bit the order of the screens to facilitate the flow and to be consistent with the code is already wrote (basically to allow db interaction which is possible in the app when the user is already authenticated)

here is the order:

- Splash
- New User / Existing User
- Code field view
- PIN view
- Connecting view(Seed generation, MQTT)
- Alias form view
- Profile Picture view
- Ready to user Sphinx
