### ISSUE TITLE
Contact creation logic

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-kotlin#685]
**Task**

- [ ] `child_pub_key` generation for new contact
- [ ] subscription and publish to get contact identity back from LSP
- [ ] key exchange back and forth to get user `contactKey` and `contactKeyRouteHint`
